# Shared computed exports for all themes.
# Theme files must set base THEME_COLOR_* values and c() before sourcing.

# === Shared semantic tokens ===
export THEME_COLOR_SURFACE_0="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_SURFACE_1=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_SURFACE_2=$(c lighten "$THEME_COLOR_BG_COLOR" 12)
export THEME_COLOR_SURFACE_3=$(c lighten "$THEME_COLOR_BG_COLOR" 18)
export THEME_COLOR_TEXT_PRIMARY="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TEXT_MUTED="$THEME_COLOR_FG_DIMMED"
export THEME_COLOR_ACCENT_PRIMARY="$THEME_COLOR_ACCENT"

# === Computed: Terminal UI ===
export THEME_COLOR_TERMINAL_SELECTION_BG_COLOR=$(c mix "$THEME_COLOR_ACCENT_PRIMARY" "$THEME_COLOR_SURFACE_0" 30)
export THEME_COLOR_TERMINAL_SELECTION_FG_COLOR="$THEME_COLOR_TEXT_PRIMARY"
export THEME_COLOR_TERMINAL_CURSOR_COLOR="$THEME_COLOR_TEXT_PRIMARY"
export THEME_COLOR_TERMINAL_CURSOR_TEXT_COLOR="$THEME_COLOR_SURFACE_0"
export THEME_COLOR_TERMINAL_URL_COLOR="$THEME_COLOR_ACCENT_PRIMARY"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_FOREGROUND="$THEME_COLOR_SURFACE_0"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_BACKGROUND="$THEME_COLOR_ACCENT_PRIMARY"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_FOREGROUND="$THEME_COLOR_TEXT_MUTED"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_BACKGROUND="$THEME_COLOR_SURFACE_1"

# === Computed: Status Bar ===
export THEME_COLOR_SELECTED_WORKSPACE="$THEME_COLOR_ACCENT_PRIMARY"
export THEME_COLOR_ACTIVE_WORKSPACE="$THEME_COLOR_SURFACE_2"
export THEME_COLOR_INACTIVE_WORKSPACE="$THEME_COLOR_SURFACE_1"

# === Computed: Vesktop ===
export THEME_COLOR_VESKTOP_BG_DARKER=$(c darken "$THEME_COLOR_SURFACE_0" 3)
export THEME_COLOR_VESKTOP_BG_MAIN=$(c lighten "$THEME_COLOR_SURFACE_0" 2)
export THEME_COLOR_VESKTOP_BG_BUTTON=$(c lighten "$THEME_COLOR_SURFACE_0" 1)
export THEME_COLOR_VESKTOP_BG_LIGHTER=$(c lighten "$THEME_COLOR_SURFACE_0" 6)
export THEME_COLOR_VESKTOP_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_TEXT_PRIMARY" 15)
export THEME_COLOR_VESKTOP_TEXT_MID=$(c mix "$THEME_COLOR_TEXT_PRIMARY" "$THEME_COLOR_TEXT_MUTED" 50)
export THEME_COLOR_VESKTOP_GRAY_DARK=$(c darken "$THEME_COLOR_TEXT_MUTED" 12)

# === Computed: Swaync ===
export THEME_COLOR_SWAYNC_BG="$THEME_COLOR_SURFACE_0"
export THEME_COLOR_SWAYNC_BG_ELEVATED="$THEME_COLOR_SURFACE_1"
export THEME_COLOR_SWAYNC_BG_HOVER="$THEME_COLOR_SURFACE_2"
export THEME_COLOR_SWAYNC_BG_ACTIVE=$(c lighten "$THEME_COLOR_SURFACE_0" 16)
export THEME_COLOR_SWAYNC_BG_PRESSED=$(c lighten "$THEME_COLOR_SURFACE_0" 22)
export THEME_COLOR_SWAYNC_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_TEXT_PRIMARY" 15)
export THEME_COLOR_SWAYNC_SLIDER=$(c mix "$THEME_COLOR_TEXT_PRIMARY" "$THEME_COLOR_TEXT_MUTED" 40)

# === Computed: Cava ===
export THEME_COLOR_CAVA_GRADIENT_1="$THEME_COLOR_CAVA_ANCHOR_A"
export THEME_COLOR_CAVA_GRADIENT_2=$(c mix "$THEME_COLOR_CAVA_ANCHOR_A" "$THEME_COLOR_CAVA_ANCHOR_B" 30)
export THEME_COLOR_CAVA_GRADIENT_3=$(c mix "$THEME_COLOR_CAVA_ANCHOR_A" "$THEME_COLOR_CAVA_ANCHOR_B" 60)
export THEME_COLOR_CAVA_GRADIENT_4="$THEME_COLOR_CAVA_ANCHOR_B"
export THEME_COLOR_CAVA_GRADIENT_5=$(c mix "$THEME_COLOR_CAVA_ANCHOR_B" "$THEME_COLOR_CAVA_ANCHOR_C" 50)
export THEME_COLOR_CAVA_GRADIENT_6="$THEME_COLOR_CAVA_ANCHOR_C"
export THEME_COLOR_CAVA_GRADIENT_7=$(c mix "$THEME_COLOR_CAVA_ANCHOR_C" "$THEME_COLOR_CAVA_ANCHOR_D" 50)
export THEME_COLOR_CAVA_GRADIENT_8="$THEME_COLOR_CAVA_ANCHOR_D"

# === Computed: Hyprland (rgba without #, with alpha suffix) ===
export THEME_COLOR_HYPR_ACTIVE_BORDER_1="$(c strip "$THEME_COLOR_ACCENT_PRIMARY")cc"
export THEME_COLOR_HYPR_ACTIVE_BORDER_2="$(c strip $(c darken "$THEME_COLOR_ACCENT_PRIMARY" 30))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_1="$(c strip "$THEME_COLOR_SURFACE_2")ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_2="$(c strip "$THEME_COLOR_SURFACE_2")55"
export THEME_COLOR_HYPR_SHADOW="$(c strip "$THEME_COLOR_SURFACE_0")ee"

# === Computed: Wofi ===
export THEME_COLOR_WOFI_BG="$THEME_COLOR_SURFACE_0"
export THEME_COLOR_WOFI_BG_INPUT="$THEME_COLOR_SURFACE_1"
export THEME_COLOR_WOFI_BG_SELECTED="$THEME_COLOR_ACCENT_PRIMARY"
export THEME_COLOR_WOFI_FG="$THEME_COLOR_TEXT_PRIMARY"
export THEME_COLOR_WOFI_FG_SELECTED="$THEME_COLOR_SURFACE_0"
export THEME_COLOR_WOFI_BORDER="$THEME_COLOR_ACCENT_PRIMARY"

# === Computed: Kitty ===
# Kitty appears slightly darker on some setups.
# Positive values lighten, negative values darken. Tweak this one value as needed.
THEME_COLOR_KITTY_TINT_COMPENSATION=2
if [ "$THEME_COLOR_KITTY_TINT_COMPENSATION" -ge 0 ]; then
	export THEME_COLOR_KITTY_BG=$(c lighten "$THEME_COLOR_BG_COLOR" "$THEME_COLOR_KITTY_TINT_COMPENSATION")
else
	export THEME_COLOR_KITTY_BG=$(c darken "$THEME_COLOR_BG_COLOR" "$((-THEME_COLOR_KITTY_TINT_COMPENSATION))")
fi
export THEME_COLOR_KITTY_FG="$THEME_COLOR_FG_COLOR"

# === Computed: VS Code ===
export THEME_COLOR_VSCODE_BG="$THEME_COLOR_SURFACE_0"
export THEME_COLOR_VSCODE_FG="$THEME_COLOR_TEXT_PRIMARY"
export THEME_COLOR_VSCODE_FG_DIMMED="$THEME_COLOR_TEXT_MUTED"
export THEME_COLOR_VSCODE_ACCENT="$THEME_COLOR_ACCENT_PRIMARY"
export THEME_COLOR_VSCODE_SELECTED_FILE_FG="$THEME_COLOR_VSCODE_ACCENT"
export THEME_COLOR_VSCODE_SELECTED_FILE_BG=$(c mix "$THEME_COLOR_VSCODE_ACCENT" "$THEME_COLOR_VSCODE_BG" 95)
export THEME_COLOR_VSCODE_GIT_ADDED_FG="$THEME_COLOR_TERMINAL_COLOR_2"
export THEME_COLOR_VSCODE_GIT_MODIFIED_FG="$THEME_COLOR_TERMINAL_COLOR_3"

export THEME_COLOR_VSCODE_TERMINAL_COLOR_0="$THEME_COLOR_TERMINAL_COLOR_0"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_1="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_2="$THEME_COLOR_TERMINAL_COLOR_2"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_3="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_4="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_5="$THEME_COLOR_TERMINAL_COLOR_5"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_6="$THEME_COLOR_TERMINAL_COLOR_6"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_7="$THEME_COLOR_TERMINAL_COLOR_7"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_8="$THEME_COLOR_TERMINAL_COLOR_8"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_9="$THEME_COLOR_TERMINAL_COLOR_9"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_10="$THEME_COLOR_TERMINAL_COLOR_10"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_11="$THEME_COLOR_TERMINAL_COLOR_11"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_12="$THEME_COLOR_TERMINAL_COLOR_12"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_13="$THEME_COLOR_TERMINAL_COLOR_13"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_14="$THEME_COLOR_TERMINAL_COLOR_14"
export THEME_COLOR_VSCODE_TERMINAL_COLOR_15="$THEME_COLOR_TERMINAL_COLOR_15"
