# ══════════════════════════════════════════════
#  Everforest — Everforest Dark Medium
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#2D353B"
export THEME_COLOR_FG_COLOR="#D3C6AA"
export THEME_COLOR_FG_DIMMED="#859289"
export THEME_COLOR_ACCENT="#A7C080"
export THEME_COLOR_BORDER="rgba(167, 192, 128, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#475258"
export THEME_COLOR_TERMINAL_COLOR_1="#E67E80"
export THEME_COLOR_TERMINAL_COLOR_2="#A7C080"
export THEME_COLOR_TERMINAL_COLOR_3="#DBBC7F"
export THEME_COLOR_TERMINAL_COLOR_4="#7FBBB3"
export THEME_COLOR_TERMINAL_COLOR_5="#D699B6"
export THEME_COLOR_TERMINAL_COLOR_6="#83C092"
export THEME_COLOR_TERMINAL_COLOR_7="#D3C6AA"
export THEME_COLOR_TERMINAL_COLOR_8="#56635C"
export THEME_COLOR_TERMINAL_COLOR_9="#F85552"
export THEME_COLOR_TERMINAL_COLOR_10="#8DA101"
export THEME_COLOR_TERMINAL_COLOR_11="#DFA000"
export THEME_COLOR_TERMINAL_COLOR_12="#3A94C5"
export THEME_COLOR_TERMINAL_COLOR_13="#DF69BA"
export THEME_COLOR_TERMINAL_COLOR_14="#35A77C"
export THEME_COLOR_TERMINAL_COLOR_15="#DFDDC8"

# === Cava anchors (theme-specific ordering) ===
export THEME_COLOR_CAVA_ANCHOR_A="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_ANCHOR_B="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_ANCHOR_C="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_ANCHOR_D="$THEME_COLOR_TERMINAL_COLOR_5"

. "$HOME/.config/theming/themes/computed_colors.sh"
