# ══════════════════════════════════════════════
#  Grayscale — One Dark
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#1A1A1A"
export THEME_COLOR_FG_COLOR="#ABB2BF"
export THEME_COLOR_FG_DIMMED="#939393"
export THEME_COLOR_ACCENT="#8E66FF"
export THEME_COLOR_BORDER="rgba(142, 102, 255, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#3F4451"
export THEME_COLOR_TERMINAL_COLOR_1="#E06C75"
export THEME_COLOR_TERMINAL_COLOR_2="#98C379"
export THEME_COLOR_TERMINAL_COLOR_3="#D19A66"
export THEME_COLOR_TERMINAL_COLOR_4="#61AFEF"
export THEME_COLOR_TERMINAL_COLOR_5="#C678DD"
export THEME_COLOR_TERMINAL_COLOR_6="#56B6C2"
export THEME_COLOR_TERMINAL_COLOR_7="#D7DAE0"
export THEME_COLOR_TERMINAL_COLOR_8="#4F5666"
export THEME_COLOR_TERMINAL_COLOR_9="#BE5046"
export THEME_COLOR_TERMINAL_COLOR_10="#A5E075"
export THEME_COLOR_TERMINAL_COLOR_11="#E5C07B"
export THEME_COLOR_TERMINAL_COLOR_12="#4DC4FF"
export THEME_COLOR_TERMINAL_COLOR_13="#DE73FF"
export THEME_COLOR_TERMINAL_COLOR_14="#4CD1E0"
export THEME_COLOR_TERMINAL_COLOR_15="#E6E6E6"

# === Cava anchors (theme-specific ordering) ===
export THEME_COLOR_CAVA_ANCHOR_A="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_ANCHOR_B="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_ANCHOR_C="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_ANCHOR_D="$THEME_COLOR_TERMINAL_COLOR_5"

. "$HOME/.config/theming/themes/computed_colors.sh"
