# ══════════════════════════════════════════════
#  Theme 2 — Everforest Dark Medium
# ══════════════════════════════════════════════
CU="$HOME/.config/custom/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#2D353B"
export THEME_COLOR_FG_COLOR="#D3C6AA"
export THEME_COLOR_FG_DIMMED="#859289"
export THEME_COLOR_ACCENT="#A7C080"
export THEME_COLOR_BORDER="rgba(167, 192, 128, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#475258"
export THEME_COLOR_TERMINAL_COLOR_1="#E67E80"
export THEME_COLOR_TERMINAL_COLOR_2="#A7C080"
export THEME_COLOR_TERMINAL_COLOR_3="#DBBC7F"
export THEME_COLOR_TERMINAL_COLOR_4="#7FBBB3"
export THEME_COLOR_TERMINAL_COLOR_5="#D699B6"
export THEME_COLOR_TERMINAL_COLOR_6="#83C092"
export THEME_COLOR_TERMINAL_COLOR_7="#D3C6AA"
export THEME_COLOR_TERMINAL_COLOR_8="#56635C"
export THEME_COLOR_TERMINAL_COLOR_9="#F85552"
export THEME_COLOR_TERMINAL_COLOR_10="#8DA101"
export THEME_COLOR_TERMINAL_COLOR_11="#DFA000"
export THEME_COLOR_TERMINAL_COLOR_12="#3A94C5"
export THEME_COLOR_TERMINAL_COLOR_13="#DF69BA"
export THEME_COLOR_TERMINAL_COLOR_14="#35A77C"
export THEME_COLOR_TERMINAL_COLOR_15="#DFDDC8"

# === Computed: Terminal UI ===
export THEME_COLOR_TERMINAL_SELECTION_BG_COLOR=$(c mix "$THEME_COLOR_ACCENT" "$THEME_COLOR_BG_COLOR" 30)
export THEME_COLOR_TERMINAL_SELECTION_FG_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_TEXT_COLOR="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_URL_COLOR="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_FOREGROUND="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_BACKGROUND="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_FOREGROUND="$THEME_COLOR_FG_DIMMED"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_BACKGROUND=$(c lighten "$THEME_COLOR_BG_COLOR" 5)

# === Computed: Status Bar ===
export THEME_COLOR_SELECTED_WORKSPACE="$THEME_COLOR_ACCENT"
export THEME_COLOR_ACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 15)
export THEME_COLOR_INACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 4)

# === Computed: Vesktop ===
export THEME_COLOR_VESKTOP_BG_DARKER=$(c darken "$THEME_COLOR_BG_COLOR" 3)
export THEME_COLOR_VESKTOP_BG_MAIN=$(c lighten "$THEME_COLOR_BG_COLOR" 2)
export THEME_COLOR_VESKTOP_BG_BUTTON=$(c lighten "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_VESKTOP_BG_LIGHTER=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_VESKTOP_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 25)
export THEME_COLOR_VESKTOP_TEXT_MID=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 50)
export THEME_COLOR_VESKTOP_GRAY_DARK=$(c darken "$THEME_COLOR_FG_DIMMED" 12)

# === Computed: Swaync ===
export THEME_COLOR_SWAYNC_BG=$(c darken "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_SWAYNC_BG_ELEVATED=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_SWAYNC_BG_HOVER=$(c lighten "$THEME_COLOR_BG_COLOR" 12)
export THEME_COLOR_SWAYNC_BG_ACTIVE=$(c lighten "$THEME_COLOR_BG_COLOR" 16)
export THEME_COLOR_SWAYNC_BG_PRESSED=$(c lighten "$THEME_COLOR_BG_COLOR" 22)
export THEME_COLOR_SWAYNC_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 15)
export THEME_COLOR_SWAYNC_SLIDER=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 40)

# === Computed: Cava ===
export THEME_COLOR_CAVA_GRADIENT_1="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_GRADIENT_2=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 30)
export THEME_COLOR_CAVA_GRADIENT_3=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 60)
export THEME_COLOR_CAVA_GRADIENT_4="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_GRADIENT_5=$(c mix "$THEME_COLOR_TERMINAL_COLOR_3" "$THEME_COLOR_TERMINAL_COLOR_4" 50)
export THEME_COLOR_CAVA_GRADIENT_6="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_GRADIENT_7=$(c mix "$THEME_COLOR_TERMINAL_COLOR_4" "$THEME_COLOR_TERMINAL_COLOR_5" 50)
export THEME_COLOR_CAVA_GRADIENT_8="$THEME_COLOR_TERMINAL_COLOR_5"

# === Computed: Hyprland (rgba without #, with alpha suffix) ===
export THEME_COLOR_HYPR_ACTIVE_BORDER_1="$(c strip "$THEME_COLOR_ACCENT")cc"
export THEME_COLOR_HYPR_ACTIVE_BORDER_2="$(c strip $(c darken "$THEME_COLOR_ACCENT" 30))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_1="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_2="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))55"
export THEME_COLOR_HYPR_SHADOW="$(c strip "$THEME_COLOR_BG_COLOR")ee"
