# ══════════════════════════════════════════════
#  Grayscale — One Dark
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#1A1A1A"
export THEME_COLOR_FG_COLOR="#ABB2BF"
export THEME_COLOR_FG_DIMMED="#939393"
export THEME_COLOR_ACCENT="#D7DAE0"
export THEME_COLOR_BORDER="rgba(255, 255, 255, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#3F4451"
export THEME_COLOR_TERMINAL_COLOR_1="#E06C75"
export THEME_COLOR_TERMINAL_COLOR_2="#98C379"
export THEME_COLOR_TERMINAL_COLOR_3="#D19A66"
export THEME_COLOR_TERMINAL_COLOR_4="#61AFEF"
export THEME_COLOR_TERMINAL_COLOR_5="#C678DD"
export THEME_COLOR_TERMINAL_COLOR_6="#56B6C2"
export THEME_COLOR_TERMINAL_COLOR_7="#D7DAE0"
export THEME_COLOR_TERMINAL_COLOR_8="#4F5666"
export THEME_COLOR_TERMINAL_COLOR_9="#BE5046"
export THEME_COLOR_TERMINAL_COLOR_10="#A5E075"
export THEME_COLOR_TERMINAL_COLOR_11="#E5C07B"
export THEME_COLOR_TERMINAL_COLOR_12="#4DC4FF"
export THEME_COLOR_TERMINAL_COLOR_13="#DE73FF"
export THEME_COLOR_TERMINAL_COLOR_14="#4CD1E0"
export THEME_COLOR_TERMINAL_COLOR_15="#E6E6E6"

# === Computed: Terminal UI ===
export THEME_COLOR_TERMINAL_SELECTION_BG_COLOR=$(c mix "$THEME_COLOR_ACCENT" "$THEME_COLOR_BG_COLOR" 30)
export THEME_COLOR_TERMINAL_SELECTION_FG_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_TEXT_COLOR="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_URL_COLOR="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_FOREGROUND="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_BACKGROUND="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_FOREGROUND="$THEME_COLOR_FG_DIMMED"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_BACKGROUND=$(c lighten "$THEME_COLOR_BG_COLOR" 5)

# === Computed: Status Bar ===
export THEME_COLOR_SELECTED_WORKSPACE="$THEME_COLOR_ACCENT"
export THEME_COLOR_ACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 15)
export THEME_COLOR_INACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 4)

# === Computed: Vesktop ===
export THEME_COLOR_VESKTOP_BG_DARKER=$(c darken "$THEME_COLOR_BG_COLOR" 3)
export THEME_COLOR_VESKTOP_BG_MAIN=$(c lighten "$THEME_COLOR_BG_COLOR" 2)
export THEME_COLOR_VESKTOP_BG_BUTTON=$(c lighten "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_VESKTOP_BG_LIGHTER=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_VESKTOP_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 25)
export THEME_COLOR_VESKTOP_TEXT_MID=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 50)
export THEME_COLOR_VESKTOP_GRAY_DARK=$(c darken "$THEME_COLOR_FG_DIMMED" 12)

# === Computed: Swaync ===
export THEME_COLOR_SWAYNC_BG=$(c darken "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_SWAYNC_BG_ELEVATED=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_SWAYNC_BG_HOVER=$(c lighten "$THEME_COLOR_BG_COLOR" 12)
export THEME_COLOR_SWAYNC_BG_ACTIVE=$(c lighten "$THEME_COLOR_BG_COLOR" 16)
export THEME_COLOR_SWAYNC_BG_PRESSED=$(c lighten "$THEME_COLOR_BG_COLOR" 22)
export THEME_COLOR_SWAYNC_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 15)
export THEME_COLOR_SWAYNC_SLIDER=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 40)

# === Computed: Cava ===
export THEME_COLOR_CAVA_GRADIENT_1="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_GRADIENT_2=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 30)
export THEME_COLOR_CAVA_GRADIENT_3=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 60)
export THEME_COLOR_CAVA_GRADIENT_4="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_GRADIENT_5=$(c mix "$THEME_COLOR_TERMINAL_COLOR_3" "$THEME_COLOR_TERMINAL_COLOR_4" 50)
export THEME_COLOR_CAVA_GRADIENT_6="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_GRADIENT_7=$(c mix "$THEME_COLOR_TERMINAL_COLOR_4" "$THEME_COLOR_TERMINAL_COLOR_5" 50)
export THEME_COLOR_CAVA_GRADIENT_8="$THEME_COLOR_TERMINAL_COLOR_5"

# === Computed: Hyprland (rgba without #, with alpha suffix) ===
export THEME_COLOR_HYPR_ACTIVE_BORDER_1="$(c strip "$THEME_COLOR_ACCENT")cc"
export THEME_COLOR_HYPR_ACTIVE_BORDER_2="$(c strip $(c darken "$THEME_COLOR_ACCENT" 30))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_1="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_2="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))55"
export THEME_COLOR_HYPR_SHADOW="$(c strip "$THEME_COLOR_BG_COLOR")ee"

# === Computed: Wofi ===
export THEME_COLOR_WOFI_BG="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_WOFI_BG_INPUT=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_WOFI_BG_SELECTED="$THEME_COLOR_ACCENT"
export THEME_COLOR_WOFI_FG="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_WOFI_FG_SELECTED="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_WOFI_BORDER="$THEME_COLOR_ACCENT"
