# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = ags run ~/.config/ags/status-bar/app.ts
exec-once = /usr/lib/geoclue-2.0/demos/agent
exec-once = ~/.config/hypr/hyprland/scripts/set_wallpaper_awww.sh
exec-once = ~/.config/hypr/hyprland/scripts/turn_on_light.sh
exec-once = dotoold
exec-once = hypridle
exec-once = swaync
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = nwg-look -a