hl.on("hyprland.start", function ()
  hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
  hl.exec_cmd("systemctl --user start xdg-desktop-portal-gtk")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("ags run ~/.config/ags/status-bar/app.ts")
  hl.exec_cmd("/usr/lib/geoclue-2.0/demos/agent")
  hl.exec_cmd("~/.config/hypr/hyprland/scripts/set_wallpaper_awww.sh")
  hl.exec_cmd("~/.config/hypr/hyprland/scripts/turn_on_light.sh")
  hl.exec_cmd("dotoold")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("swaync")
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("nwg-look -a")

  hl.exec_cmd("systemctl --user start sunshine")
  hl.exec_cmd("systemctl --user start mybar")
end)