# Set programs that you use

$terminal = kitty
$fileManager = nautilus --new-window
$menu = wofi --show drun --no-actions
$browser = zen-browser
$codeEditor = code
$defaultMessagingApp = beeper
$musicPlayer = spotify

$notificationPanel = swaync-client -t

$reloadMybar = systemctl --user restart mybar.service