# Set programs that you use

$terminal = kitty
$fileManager = nautilus --new-window
$menu = wofi --show drun --no-actions
$browser = zen-browser
$codeEditor = code
$defaultMessagingApp = beeper
$musicPlayer = spotify

$notificationPanel = swaync-client -t

$reloadMybar = pkill -f "gjs" 2>/dev/null & ags run ~/.config/ags/status-bar/app.ts