windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = browser-rule
    match:class = ^(zen)$
    workspace = 1
}

windowrule {
    name = code-rule
    match:class = ^(code)$
    workspace = 2
}

windowrule {
    name = spotify-rule
    match:class = ^(spotify)$
    workspace = 8
}

windowrule {
    name = beeper-rule
    match:class = ^(BeeperTexts)$
    float = true
}