# ══════════════════════════════════════════════
#  Summer — Sunset (Vibrant Orange)
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#1F1714"
export THEME_COLOR_FG_COLOR="#E8D5C4"
export THEME_COLOR_FG_DIMMED="#9A8776"
export THEME_COLOR_ACCENT="#FF8C42"
export THEME_COLOR_BORDER="rgba(255, 140, 66, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#4A3A2E"
export THEME_COLOR_TERMINAL_COLOR_1="#FF6B6B"
export THEME_COLOR_TERMINAL_COLOR_2="#A8CC60"
export THEME_COLOR_TERMINAL_COLOR_3="#FFB347"
export THEME_COLOR_TERMINAL_COLOR_4="#6AB0DE"
export THEME_COLOR_TERMINAL_COLOR_5="#E88FCF"
export THEME_COLOR_TERMINAL_COLOR_6="#66CCAA"
export THEME_COLOR_TERMINAL_COLOR_7="#E8D5C4"
export THEME_COLOR_TERMINAL_COLOR_8="#5C4B3E"
export THEME_COLOR_TERMINAL_COLOR_9="#FF4444"
export THEME_COLOR_TERMINAL_COLOR_10="#B5E06E"
export THEME_COLOR_TERMINAL_COLOR_11="#FFCC66"
export THEME_COLOR_TERMINAL_COLOR_12="#7EC8E3"
export THEME_COLOR_TERMINAL_COLOR_13="#F4A0D8"
export THEME_COLOR_TERMINAL_COLOR_14="#7DDDB8"
export THEME_COLOR_TERMINAL_COLOR_15="#F5E6D8"

# === Computed: Terminal UI ===
export THEME_COLOR_TERMINAL_SELECTION_BG_COLOR=$(c mix "$THEME_COLOR_ACCENT" "$THEME_COLOR_BG_COLOR" 30)
export THEME_COLOR_TERMINAL_SELECTION_FG_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_TEXT_COLOR="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_URL_COLOR="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_FOREGROUND="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_BACKGROUND="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_FOREGROUND="$THEME_COLOR_FG_DIMMED"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_BACKGROUND=$(c lighten "$THEME_COLOR_BG_COLOR" 5)

# === Computed: Status Bar ===
export THEME_COLOR_SELECTED_WORKSPACE="$THEME_COLOR_ACCENT"
export THEME_COLOR_ACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 15)
export THEME_COLOR_INACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 4)

# === Computed: Vesktop ===
export THEME_COLOR_VESKTOP_BG_DARKER=$(c darken "$THEME_COLOR_BG_COLOR" 3)
export THEME_COLOR_VESKTOP_BG_MAIN=$(c lighten "$THEME_COLOR_BG_COLOR" 2)
export THEME_COLOR_VESKTOP_BG_BUTTON=$(c lighten "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_VESKTOP_BG_LIGHTER=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_VESKTOP_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 25)
export THEME_COLOR_VESKTOP_TEXT_MID=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 50)
export THEME_COLOR_VESKTOP_GRAY_DARK=$(c darken "$THEME_COLOR_FG_DIMMED" 12)

# === Computed: Swaync ===
export THEME_COLOR_SWAYNC_BG=$(c darken "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_SWAYNC_BG_ELEVATED=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_SWAYNC_BG_HOVER=$(c lighten "$THEME_COLOR_BG_COLOR" 12)
export THEME_COLOR_SWAYNC_BG_ACTIVE=$(c lighten "$THEME_COLOR_BG_COLOR" 16)
export THEME_COLOR_SWAYNC_BG_PRESSED=$(c lighten "$THEME_COLOR_BG_COLOR" 22)
export THEME_COLOR_SWAYNC_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 15)
export THEME_COLOR_SWAYNC_SLIDER=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 40)

# === Computed: Cava ===
export THEME_COLOR_CAVA_GRADIENT_1="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_GRADIENT_2=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 30)
export THEME_COLOR_CAVA_GRADIENT_3=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 60)
export THEME_COLOR_CAVA_GRADIENT_4="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_GRADIENT_5=$(c mix "$THEME_COLOR_TERMINAL_COLOR_3" "$THEME_COLOR_TERMINAL_COLOR_4" 50)
export THEME_COLOR_CAVA_GRADIENT_6="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_GRADIENT_7=$(c mix "$THEME_COLOR_TERMINAL_COLOR_4" "$THEME_COLOR_TERMINAL_COLOR_5" 50)
export THEME_COLOR_CAVA_GRADIENT_8="$THEME_COLOR_TERMINAL_COLOR_5"

# === Computed: Hyprland (rgba without #, with alpha suffix) ===
export THEME_COLOR_HYPR_ACTIVE_BORDER_1="$(c strip "$THEME_COLOR_ACCENT")cc"
export THEME_COLOR_HYPR_ACTIVE_BORDER_2="$(c strip $(c darken "$THEME_COLOR_ACCENT" 30))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_1="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_2="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))55"
export THEME_COLOR_HYPR_SHADOW="$(c strip "$THEME_COLOR_BG_COLOR")ee"

# === Computed: Wofi ===
export THEME_COLOR_WOFI_BG="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_WOFI_BG_INPUT=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_WOFI_BG_SELECTED="$THEME_COLOR_ACCENT"
export THEME_COLOR_WOFI_FG="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_WOFI_FG_SELECTED="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_WOFI_BORDER="$THEME_COLOR_ACCENT"
