# ══════════════════════════════════════════════
#  Summer — Sunset (Vibrant Orange)
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#1F1714"
export THEME_COLOR_FG_COLOR="#E8D5C4"
export THEME_COLOR_FG_DIMMED="#9A8776"
export THEME_COLOR_ACCENT="#FF8C42"
export THEME_COLOR_BORDER="rgba(255, 140, 66, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#4A3A2E"
export THEME_COLOR_TERMINAL_COLOR_1="#FF6B6B"
export THEME_COLOR_TERMINAL_COLOR_2="#A8CC60"
export THEME_COLOR_TERMINAL_COLOR_3="#FFB347"
export THEME_COLOR_TERMINAL_COLOR_4="#6AB0DE"
export THEME_COLOR_TERMINAL_COLOR_5="#E88FCF"
export THEME_COLOR_TERMINAL_COLOR_6="#66CCAA"
export THEME_COLOR_TERMINAL_COLOR_7="#E8D5C4"
export THEME_COLOR_TERMINAL_COLOR_8="#5C4B3E"
export THEME_COLOR_TERMINAL_COLOR_9="#FF4444"
export THEME_COLOR_TERMINAL_COLOR_10="#B5E06E"
export THEME_COLOR_TERMINAL_COLOR_11="#FFCC66"
export THEME_COLOR_TERMINAL_COLOR_12="#7EC8E3"
export THEME_COLOR_TERMINAL_COLOR_13="#F4A0D8"
export THEME_COLOR_TERMINAL_COLOR_14="#7DDDB8"
export THEME_COLOR_TERMINAL_COLOR_15="#F5E6D8"

# === Cava anchors (theme-specific ordering) ===
export THEME_COLOR_CAVA_ANCHOR_A="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_ANCHOR_B="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_ANCHOR_C="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_ANCHOR_D="$THEME_COLOR_TERMINAL_COLOR_5"

. "$HOME/.config/theming/themes/computed_colors.sh"
