# ══════════════════════════════════════════════
#  Cold — Frost (Winter Blue)
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#151B23"
export THEME_COLOR_FG_COLOR="#A8D1FF"
export THEME_COLOR_FG_DIMMED="#5C85B2"
export THEME_COLOR_ACCENT="#7ABAFF"
export THEME_COLOR_BORDER="rgba(122, 186, 255, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#2C3847"
export THEME_COLOR_TERMINAL_COLOR_1="#E06C75"
export THEME_COLOR_TERMINAL_COLOR_2="#88C0A0"
export THEME_COLOR_TERMINAL_COLOR_3="#D4B97D"
export THEME_COLOR_TERMINAL_COLOR_4="#7ABAFF"
export THEME_COLOR_TERMINAL_COLOR_5="#B48EAD"
export THEME_COLOR_TERMINAL_COLOR_6="#8FBCDB"
export THEME_COLOR_TERMINAL_COLOR_7="#C0CEDB"
export THEME_COLOR_TERMINAL_COLOR_8="#3D4F63"
export THEME_COLOR_TERMINAL_COLOR_9="#D45B65"
export THEME_COLOR_TERMINAL_COLOR_10="#9FD4B0"
export THEME_COLOR_TERMINAL_COLOR_11="#E5CC8E"
export THEME_COLOR_TERMINAL_COLOR_12="#5DA3E6"
export THEME_COLOR_TERMINAL_COLOR_13="#C99FBD"
export THEME_COLOR_TERMINAL_COLOR_14="#A3D0EB"
export THEME_COLOR_TERMINAL_COLOR_15="#DAE4ED"

# === Cava anchors (theme-specific ordering) ===
export THEME_COLOR_CAVA_ANCHOR_A="$THEME_COLOR_TERMINAL_COLOR_6"
export THEME_COLOR_CAVA_ANCHOR_B="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_ANCHOR_C="$THEME_COLOR_TERMINAL_COLOR_5"
export THEME_COLOR_CAVA_ANCHOR_D="$THEME_COLOR_TERMINAL_COLOR_1"

. "$HOME/.config/theming/themes/computed_colors.sh"
