# ══════════════════════════════════════════════
#  Mocha — Catppuccin
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#1E1E2E"
export THEME_COLOR_FG_COLOR="#CDD6F4"
export THEME_COLOR_FG_DIMMED="#A6ADC8"
export THEME_COLOR_ACCENT="#FAB387" # Peach (The vibrant orange)
export THEME_COLOR_BORDER="rgba(250, 179, 135, 0.8)"

# === ANSI Palette (Mocha) ===
export THEME_COLOR_TERMINAL_COLOR_0="#45475A" # Surface 1
export THEME_COLOR_TERMINAL_COLOR_1="#F38BA8" # Red
export THEME_COLOR_TERMINAL_COLOR_2="#A6E3A1" # Green
export THEME_COLOR_TERMINAL_COLOR_3="#F9E2AF" # Yellow
export THEME_COLOR_TERMINAL_COLOR_4="#89B4FA" # Blue
export THEME_COLOR_TERMINAL_COLOR_5="#F5C2E7" # Pink
export THEME_COLOR_TERMINAL_COLOR_6="#94E2D5" # Teal
export THEME_COLOR_TERMINAL_COLOR_7="#BAC2DE" # Subtext 1
export THEME_COLOR_TERMINAL_COLOR_8="#585B70" # Surface 2
export THEME_COLOR_TERMINAL_COLOR_9="#F38BA8" # Red
export THEME_COLOR_TERMINAL_COLOR_10="#A6E3A1" # Green
export THEME_COLOR_TERMINAL_COLOR_11="#F9E2AF" # Yellow
export THEME_COLOR_TERMINAL_COLOR_12="#89B4FA" # Blue
export THEME_COLOR_TERMINAL_COLOR_13="#F5C2E7" # Pink
export THEME_COLOR_TERMINAL_COLOR_14="#94E2D5" # Teal
export THEME_COLOR_TERMINAL_COLOR_15="#A6ADC8" # Subtext 0

# === Computed: Terminal UI ===
export THEME_COLOR_TERMINAL_SELECTION_BG_COLOR=$(c mix "$THEME_COLOR_ACCENT" "$THEME_COLOR_BG_COLOR" 30)
export THEME_COLOR_TERMINAL_SELECTION_FG_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_COLOR="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_TERMINAL_CURSOR_TEXT_COLOR="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_URL_COLOR="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_FOREGROUND="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_TERMINAL_ACTIVE_TAB_BACKGROUND="$THEME_COLOR_ACCENT"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_FOREGROUND="$THEME_COLOR_FG_DIMMED"
export THEME_COLOR_TERMINAL_INACTIVE_TAB_BACKGROUND=$(c lighten "$THEME_COLOR_BG_COLOR" 5)

# === Computed: Status Bar ===
export THEME_COLOR_SELECTED_WORKSPACE="$THEME_COLOR_ACCENT"
export THEME_COLOR_ACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 15)
export THEME_COLOR_INACTIVE_WORKSPACE=$(c lighten "$THEME_COLOR_BG_COLOR" 4)

# === Computed: Vesktop ===
export THEME_COLOR_VESKTOP_BG_DARKER=$(c darken "$THEME_COLOR_BG_COLOR" 3)
export THEME_COLOR_VESKTOP_BG_MAIN=$(c lighten "$THEME_COLOR_BG_COLOR" 2)
export THEME_COLOR_VESKTOP_BG_BUTTON=$(c lighten "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_VESKTOP_BG_LIGHTER=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_VESKTOP_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 25)
export THEME_COLOR_VESKTOP_TEXT_MID=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 50)
export THEME_COLOR_VESKTOP_GRAY_DARK=$(c darken "$THEME_COLOR_FG_DIMMED" 12)

# === Computed: Swaync ===
export THEME_COLOR_SWAYNC_BG=$(c darken "$THEME_COLOR_BG_COLOR" 1)
export THEME_COLOR_SWAYNC_BG_ELEVATED=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_SWAYNC_BG_HOVER=$(c lighten "$THEME_COLOR_BG_COLOR" 12)
export THEME_COLOR_SWAYNC_BG_ACTIVE=$(c lighten "$THEME_COLOR_BG_COLOR" 16)
export THEME_COLOR_SWAYNC_BG_PRESSED=$(c lighten "$THEME_COLOR_BG_COLOR" 22)
export THEME_COLOR_SWAYNC_TEXT_BRIGHT=$(c lighten "$THEME_COLOR_FG_COLOR" 15)
export THEME_COLOR_SWAYNC_SLIDER=$(c mix "$THEME_COLOR_FG_COLOR" "$THEME_COLOR_FG_DIMMED" 40)

# === Computed: Cava ===
export THEME_COLOR_CAVA_GRADIENT_1="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_GRADIENT_2=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 30)
export THEME_COLOR_CAVA_GRADIENT_3=$(c mix "$THEME_COLOR_TERMINAL_COLOR_1" "$THEME_COLOR_TERMINAL_COLOR_3" 60)
export THEME_COLOR_CAVA_GRADIENT_4="$THEME_COLOR_TERMINAL_COLOR_3"
export THEME_COLOR_CAVA_GRADIENT_5=$(c mix "$THEME_COLOR_TERMINAL_COLOR_3" "$THEME_COLOR_TERMINAL_COLOR_4" 50)
export THEME_COLOR_CAVA_GRADIENT_6="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_GRADIENT_7=$(c mix "$THEME_COLOR_TERMINAL_COLOR_4" "$THEME_COLOR_TERMINAL_COLOR_5" 50)
export THEME_COLOR_CAVA_GRADIENT_8="$THEME_COLOR_TERMINAL_COLOR_5"

# === Computed: Hyprland (rgba without #, with alpha suffix) ===
export THEME_COLOR_HYPR_ACTIVE_BORDER_1="$(c strip "$THEME_COLOR_ACCENT")cc"
export THEME_COLOR_HYPR_ACTIVE_BORDER_2="$(c strip $(c darken "$THEME_COLOR_ACCENT" 30))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_1="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))ff"
export THEME_COLOR_HYPR_INACTIVE_BORDER_2="$(c strip $(c lighten "$THEME_COLOR_BG_COLOR" 10))55"
export THEME_COLOR_HYPR_SHADOW="$(c strip "$THEME_COLOR_BG_COLOR")ee"

# === Computed: Wofi ===
export THEME_COLOR_WOFI_BG="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_WOFI_BG_INPUT=$(c lighten "$THEME_COLOR_BG_COLOR" 6)
export THEME_COLOR_WOFI_BG_SELECTED="$THEME_COLOR_ACCENT"
export THEME_COLOR_WOFI_FG="$THEME_COLOR_FG_COLOR"
export THEME_COLOR_WOFI_FG_SELECTED="$THEME_COLOR_BG_COLOR"
export THEME_COLOR_WOFI_BORDER="$THEME_COLOR_ACCENT"
