# ══════════════════════════════════════════════
#  Purple — Amethyst (Deep Purple)
# ══════════════════════════════════════════════
CU="$HOME/.config/theming/color-util.py"
c() { python3 "$CU" "$@"; }

# === Main Colors ===
export THEME_COLOR_BG_COLOR="#1A1626"
export THEME_COLOR_FG_COLOR="#D4CCE0"
export THEME_COLOR_FG_DIMMED="#8B7FA3"
export THEME_COLOR_ACCENT="#B48EFF"
export THEME_COLOR_BORDER="rgba(180, 142, 255, 0.8)"

# === ANSI Palette ===
export THEME_COLOR_TERMINAL_COLOR_0="#332F45"
export THEME_COLOR_TERMINAL_COLOR_1="#E06C8E"
export THEME_COLOR_TERMINAL_COLOR_2="#92CC8A"
export THEME_COLOR_TERMINAL_COLOR_3="#D4A85C"
export THEME_COLOR_TERMINAL_COLOR_4="#7B93E8"
export THEME_COLOR_TERMINAL_COLOR_5="#C17DCF"
export THEME_COLOR_TERMINAL_COLOR_6="#7CC2B0"
export THEME_COLOR_TERMINAL_COLOR_7="#D4CCE0"
export THEME_COLOR_TERMINAL_COLOR_8="#46415B"
export THEME_COLOR_TERMINAL_COLOR_9="#F05A7E"
export THEME_COLOR_TERMINAL_COLOR_10="#A0DB98"
export THEME_COLOR_TERMINAL_COLOR_11="#E4BC6A"
export THEME_COLOR_TERMINAL_COLOR_12="#8CA6F0"
export THEME_COLOR_TERMINAL_COLOR_13="#D48EDE"
export THEME_COLOR_TERMINAL_COLOR_14="#8CD4C0"
export THEME_COLOR_TERMINAL_COLOR_15="#E8E1F0"

# === Cava anchors (theme-specific ordering) ===
export THEME_COLOR_CAVA_ANCHOR_A="$THEME_COLOR_TERMINAL_COLOR_1"
export THEME_COLOR_CAVA_ANCHOR_B="$THEME_COLOR_TERMINAL_COLOR_5"
export THEME_COLOR_CAVA_ANCHOR_C="$THEME_COLOR_TERMINAL_COLOR_4"
export THEME_COLOR_CAVA_ANCHOR_D="$THEME_COLOR_TERMINAL_COLOR_6"

. "$HOME/.config/theming/themes/computed_colors.sh"
